# Generated by Django 5.2.4 on 2025-07-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pasajero', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_viaje', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
