# Generated by Django 5.2.4 on 2025-07-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='boletos',
            new_name='Boleto',
        ),
    ]
