# Generated by Django 5.2.4 on 2025-07-31 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0002_rename_boletos_boleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('numero_interno', models.CharField(max_length=20)),
                ('chofer', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='boleto',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletos.bus'),
        ),
    ]
