# Generated by Django 5.2.4 on 2025-08-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0003_bus_boleto_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='asiento',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='capacidad',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
